apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: RepoNameTemplate-solution
  tags:
    - dotnet
  annotations:
    backstage.io/techdocs-ref: dir:..
    coe/domain: DomainTemplate
    coe/domain-prefix: DomainPrefixTemplate
    coe/k8s-namespace: K8sNamespaceTemplate
spec:
  type: solution
  lifecycle: production
  owner: TeamTemplate
  system: SystemTemplate
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: RepoNameTemplate-solution-data
spec:
  targets:
    - /src/EntrypointFullNamespace/catalog-info.yaml