site_name: 'RepoNameTemplate docs'

nav:
  - Home: index.md
  - AppNameTemplate:
    - Home: AppNameTemplate/index.md
#if (IsWebApi)
    - Error Catalog: AppNameTemplate/error-catalog.md
    - Api Client: AppNameTemplate/api-client.md
#endif
plugins:
  - techdocs-core