apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "AppNameTemplate.fullname" . }}
  labels:
{{ include "AppNameTemplate.labels" . | indent 4 }}
  annotations:
    sidecar.jaegertracing.io/inject: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "AppNameTemplate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "AppNameTemplate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        metrics.dynatrace.com/scrape: 'true'
        metrics.dynatrace.com/path: '/metrics'
        metrics.dynatrace.com/port: '8080'
        metrics.dynatrace.com/secure: 'false'
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 3
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 3
            initialDelaySeconds: 7
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.aspnetcore_environment }}"
            - name: Spring__Cloud__Config__Uri
              value: "{{ .Values.spring_config_uri }}"
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              value: "{{ .Values.applicationInsights.instrumentationKey }}"
            {{- if .Values.proxy.enabled -}}
            {{ toYaml .Values.proxy.envVars | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
