{{- if not .Values.openshift.enabled -}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "AppNameTemplate.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $pathtype:= .Values.ingress.pathtype}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "AppNameTemplate.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      - {{ first ( get .hosts $.Values.kubernetes_environment ) }}      
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range ( get $.Values.ingress.hosts $.Values.kubernetes_environment ) }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ $pathtype}}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}  
